apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: fkzfq9fkp-go 
  janus-idp.io/tekton: fkzfq9fkp-go
  backstage.io/kubernetes-id: fkzfq9fkp-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fkzfq9fkp-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml